# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
