# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('action', models.IntegerField(verbose_name='فعالیت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'مدیریت تراکنش\u200cها',
                'verbose_name_plural': 'مدیریت تراکنش\u200cها',
            },
        ),
    ]
