# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20160606_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeduser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='آدرس ایمیل'),
        ),
    ]
