# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='سهم کاربر')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان به روزرسانی')),
            ],
            options={
                'verbose_name_plural': 'مدیریت سهم خرید کاربران',
                'verbose_name': 'مدیریت سهم خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان خرید')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت اعضا')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان به روزرسانی')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupApp.Group', verbose_name='گروه')),
            ],
            options={
                'verbose_name_plural': 'مدیریت خرید کاربران',
                'verbose_name': 'مدیریت خرید کاربران',
            },
        ),
        migrations.AddField(
            model_name='portion',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseApp.Purchase', verbose_name='خرید'),
        ),
        migrations.AddField(
            model_name='portion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
