# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseApp', '0002_auto_20160607_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
